### ISSUE TITLE
Support for any arbitrary type

### ISSUE THREAD

**Issue by sashah87** [yez/validates_type#2]
Is there any reason to not allow any Class or Module as an argument?
Eg:
When I have a class called `PhotoAlbum` in my app which I use to serialize a column called `photo_ids`. I would like to add a validation as such:
```ruby
 validates_type :photo_ids, PhotoAlbum, allow_blank: true
```
Allowing a constant as an argument will mean that the validator itself will not have to deal with constantizing a symbol and `UnknownConstant` errors.

Happy to submit a patch if there is no good reason not to.

**Comment by yez** [comment]
I would like to maintain the `:symbol` behaviour along with this `Constant` behaviour. Happy to see both versions at the same time.

Patch away!
